if [[ -s "${HOME}/.zprezto/init.zsh" ]]; then
  source "${HOME}/.zprezto/init.zsh"
fi

if [[ -e ${HOME}/.zshrc_common ]]; then
  source ${HOME}/.zshrc_common
fi

if [[ -e ${HOME}/.at_work ]]; then
  source ${HOME}/.zshrc_work
else
  source ${HOME}/.zshrc_home
fi
