if [[ -e $HOME/.at_google ]]; then
  source $HOME/.zshrc_google
else
  source $HOME/.zshrc_home
fi

alias ta="tmux attach"
alias tl="tmux list-sessions"
alias urldecode="python -c \"import sys, urllib as ul; \
  print ul.unquote_plus(sys.argv[1])\""
alias urlencode="python -c \"import sys, urllib as ul; \
  print ul.quote_plus(sys.argv[1])\""

# Fuzzy Finder
# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag --hidden --nogroup -l -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# So Ctrl-s doesn't freeze my terminal
# http://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon
