#!/bin/zsh

cd ~/Dropbox/docs

echo "========================================================================="
echo "Syncing files to Google Drive"
echo "========================================================================="
rsync -avPhR --delete . ~/GoogleDrive/docs

echo 

echo "========================================================================="
echo "Syncing files to Sync.com"
echo "========================================================================="
rsync -avPhR --delete . ~/Sync/docs
